# Generated by Django 6.0 on 2025-12-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
