# Generated by Django 6.0 on 2025-12-17 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_autor_options_rename_nome_autor_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='lancamento',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
