# Generated by Django 6.0 on 2025-12-17 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='lancamento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
