# Generated by Django 6.0 on 2025-12-17 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='livros.editora'),
        ),
    ]
